theme: jekyll-theme-minimal
title: Hassen Morad
description: Aspiring Data Scientist
<img src="assets/Pyramids2.png" alt="hi" class="inline"/>
![Giza Pyramids](https://github.com/hassenmorad/hassenmorad.github.io/blob/master/assets/Pyramids2.png)
